/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_laser_dot_brightness: 400
    stereo:
      i_subpixel: true
      i_extended_disp: false
      i_depth_filter_size: 3 # median filter
      i_enable_temporal_filter: true
      i_enable_threshold_filter: false
      i_enable_speckle_filter: false
      i_enable_decimation_filter: true
      i_enable_spatial_filter: false
      i_decimation_filter_decimation_factor: 2
      i_decimation_filter_decimation_mode: PIXEL_SKIPPING # NON_ZERO_MEAN | PIXEL_SKIPPING
      i_enable_distortion_correction: false
      i_lr_check: false
      i_output_disparity: false
      i_publish_synced_rect_pair: true
      i_bilateral_sigma: 25535
      #i_disparity_width: DISPARITY_64
      i_depth_preset: HIGH_DENSITY
    rgb:
      i_resolution: 1080P
      r_set_man_focus: true
      r_focus: 127
    left:
      i_resolution: 720P
      i_publish_topic: false
    right:
      i_resolution: 720P
      i_publish_topic: false
